INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Happy Hunting", "Gaming", 2000000, "January 2nd, 2020", "March 2nd, 2020");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("STYD", "E-Commerce", 3000000, "February 2nd, 2020", "April 2nd, 2020");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("EarWorm", "Music", 4000000, "December 2nd, 2020", "January 14th, 2021");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("ClosetHopper", "E-Commerce", 5000000, "April 23rd, 2020", "June 2nd, 2020");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("NoNoNoGram", "Gaming", 6000000, "May 2nd, 2020", "October 2nd, 2020");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Mindful Minute", "Self-Help", 7000000, "August 2nd, 2020", "September 2nd, 2020");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Alley Finder", "Gaming", 8000000, "January 2nd, 2020", "March 2nd, 2020");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("DarkRoomDevelop", "Photography", 7000000, "November 2nd, 2020", "December 2nd, 2020");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("LaTiDo", "Music", 6000000, "February 2nd, 2020", "April 2nd, 2020");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("F Is For Friends", "Social Network", 5000000, "January 2nd, 2020", "March 2nd, 2020");

INSERT INTO users(name, age) VALUES ("Spongebob",29);
INSERT INTO users(name, age) VALUES ("Patrick", 30);
INSERT INTO users(name, age) VALUES ("Wanda", 200);
INSERT INTO users(name, age) VALUES ("Cosmo", 201);
INSERT INTO users(name, age) VALUES ("Phineas",32 );
INSERT INTO users(name, age) VALUES ("Darwin", 25);
INSERT INTO users(name, age) VALUES ("Raven", 35);
INSERT INTO users(name, age) VALUES ("Chloe", 29);
INSERT INTO users(name, age) VALUES ("Halle", 28);
INSERT INTO users(name, age) VALUES ("Jessie", 34);
INSERT INTO users(name, age) VALUES ("Mark", 58);
INSERT INTO users(name, age) VALUES ("Alex", 40);
INSERT INTO users(name, age) VALUES ("Lauryn", 40);
INSERT INTO users(name, age) VALUES ("Jill", 42);
INSERT INTO users(name, age) VALUES ("Maggie", 33);
INSERT INTO users(name, age) VALUES ("Ros", 38);
INSERT INTO users(name, age) VALUES ("Stockard", 60);
INSERT INTO users(name, age) VALUES ("Goldie", 63);
INSERT INTO users(name, age) VALUES ("Ru", 45);
INSERT INTO users(name, age) VALUES ("Nicole", 45);

INSERT INTO pledges(amount, user_id, project_id) VALUES (20000, 1, 1);
INSERT INTO pledges(amount, user_id, project_id) VALUES (20000, 20,1);
INSERT INTO pledges(amount, user_id, project_id) VALUES (10000,2,1);
INSERT INTO pledges(amount, user_id, project_id) VALUES (50000,19,2);
INSERT INTO pledges(amount, user_id, project_id) VALUES (60000,3,2);
INSERT INTO pledges(amount, user_id, project_id) VALUES (70000,18,2);
INSERT INTO pledges(amount, user_id, project_id) VALUES (50000,4,3);
INSERT INTO pledges(amount, user_id, project_id) VALUES (30000,17,3);
INSERT INTO pledges(amount, user_id, project_id) VALUES (20000,14, 3);
INSERT INTO pledges(amount, user_id, project_id) VALUES (1000000,15,4);
INSERT INTO pledges(amount, user_id, project_id) VALUES (10000,5,4);
INSERT INTO pledges(amount, user_id, project_id) VALUES (50000,6,4);
INSERT INTO pledges(amount, user_id, project_id) VALUES (60000,7,5);
INSERT INTO pledges(amount, user_id, project_id) VALUES (1000000,8,5);
INSERT INTO pledges(amount, user_id, project_id) VALUES (180000,9,5);
INSERT INTO pledges(amount, user_id, project_id) VALUES (200000,10,6);
INSERT INTO pledges(amount, user_id, project_id) VALUES (90000,11,6);
INSERT INTO pledges(amount, user_id, project_id) VALUES (45000,12,6);
INSERT INTO pledges(amount, user_id, project_id) VALUES (105000,13,7);
INSERT INTO pledges(amount, user_id, project_id) VALUES (210000,14,7);
INSERT INTO pledges(amount, user_id, project_id) VALUES (305000,15,8);
INSERT INTO pledges(amount, user_id, project_id) VALUES (400000,16,8);
INSERT INTO pledges(amount, user_id, project_id) VALUES (550000,17,8);
INSERT INTO pledges(amount, user_id, project_id) VALUES (675000,18,8);
INSERT INTO pledges(amount, user_id, project_id) VALUES (90000,19,9);
INSERT INTO pledges(amount, user_id, project_id) VALUES (150000,20,10);
INSERT INTO pledges(amount, user_id, project_id) VALUES (300000,10,10);
INSERT INTO pledges(amount, user_id, project_id) VALUES (350000,19,10);
INSERT INTO pledges(amount, user_id, project_id) VALUES (225000,15,10);
INSERT INTO pledges(amount, user_id, project_id) VALUES (375000,12,10);